FROM python:3.9

RUN apt-get update && apt-get -y upgrade && apt-get install -y libgeos3.11.1 libgeos-c1v5

RUN pip install --upgrade pip

WORKDIR /opt/app-root/src/georef-ar-api

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .