FROM python:3.11-trixie

RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y locales libgeos3.13.1 libgeos-c1v5 proj-bin proj-data libproj-dev git
RUN apt-get install -y build-essential g++
RUN apt-get install -y gdal-bin python3-gdal libgdal-dev libgdal36

# Configurar locales
RUN sed -i '/es_ES.UTF-8/s/^# //g' /etc/locale.gen && locale-gen es_ES.UTF-8
ENV LANG=es_ES.UTF-8
ENV LANGUAGE=es_ES:es
ENV LC_ALL=es_ES.UTF-8

RUN rm -rf /var/lib/apt/lists/*rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

WORKDIR /opt/app-root/src/georef-ar-api

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .